apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-api
  namespace: hospital
  labels:
    app: hospital-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-api
  template:
    metadata:
      labels:
        app: hospital-api
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z postgres 5432; do
                echo "Waiting for DB..."
                sleep 3
              done
              echo "DB is ready"
      containers:
        - name: hospital-api
          image: ashrafkhan0277/hospital-backend:15
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: hospital-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: hospital-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hospital-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: hospital-secrets
                  key: POSTGRES_DB
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hospital-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@postgres:5432/$(DB_NAME)"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"