apiVersion: v1
kind: Secret
metadata:
  name: hospital-secrets
  namespace: hospital
  labels:
    app.kubernetes.io/part-of: hospital
type: Opaque
data:
  # "postgres"
  POSTGRES_USER: cG9zdGdyZXM=
  # "hospital_db"
  POSTGRES_DB: aG9zcGl0YWxfZGI=
  # "root"
  POSTGRES_PASSWORD: cm9vdA==
  # "mysecretkey"
  SECRET_KEY: bXlzZWNyZXRrZXk=