apiVersion: v1
kind: ServiceAccount
metadata:
  name: hospital-api-sa
  namespace: hospital
  labels:
    app: hospital-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hospital-admin-sa
  namespace: hospital
  labels:
    app: hospital-admin
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hospital-user-sa
  namespace: hospital
  labels:
    app: hospital-user
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hospital-db-sa
  namespace: hospital
  labels:
    app: hospital-db
automountServiceAccountToken: false